### ISSUE TITLE
mremotng migration not working

### ISSUE THREAD

**Issue by leffu33** [P-St/Migrate2WinSSHTerm#10]
After run exe file I choose `mRemoteNG` next I point connection xml and I recive:
![obraz](https://user-images.githubusercontent.com/24544254/227214733-b234b0d6-4fbe-4e1d-accd-96138b424a94.png)

Have any Idea why? 
I try protected file first but after moving connection file to unprotected still same error.

**Comment by leffu33** [comment]
after run version 0.8 everything work fine. I will close that one.

**Comment by P-St** [comment]
Thanks, this is fixed in release 0.15
