### ISSUE TITLE
import kitty portable error

### ISSUE THREAD

**Issue by runalsh** [P-St/Migrate2WinSSHTerm#12]
When trying to import kitty portable session get this error
"module urllib has no attribute unquote"

Whats not helped:
adding _from urllib.parse import quote_ 
installing with pip praat-parselmouth
addidn import urllib.parse

Python version 3.12 x64
Windows 11 x64

**Comment by P-St** [comment]
Thanks for your feedback. This bug should be fixed in the current version 0.18
