### ISSUE TITLE
Place the connections.xml into the folder WinSSHTerm/config/

### ISSUE THREAD

**Issue by simonschaufi** [P-St/Migrate2WinSSHTerm#2]
Hello, I put the file in `C:\Program Files (x86)\WinSSHTerm\config` but WinSSHTerm doesn't pick it up. What am I doing wrong?

WinSSHTerm version 2.1.2

**Comment by P-St** [comment]
Hi,

if you use the installer edition of WinSSHTerm then you'll find a WinSSHTerm folder in your documents folder. This is the right one.

I'll add this to the readme, because it's missing. Thanks

**Comment by simonschaufi** [comment]
thank you, that worked!
