### ISSUE TITLE
Migrate from mRemoteNG

### ISSUE THREAD

**Issue by luisely** [P-St/Migrate2WinSSHTerm#3]
Migrate from mRemoteNG

I open the Migrate2WinSSHTerm.exe, click on mRemoteNG, choose my XML file...nothing happens.

Can help me?

**Comment by P-St** [comment]
Which version of mRemoteNG are you using?

**Comment by luisely** [comment]
1.76.4.16229

**Comment by P-St** [comment]
Thanks, I fixed a bug in version 0.5. Is it working for you?

**Comment by luisely** [comment]
Perfect! it Works! 

very thanks!!
