### ISSUE TITLE
Font overlap

### ISSUE THREAD

**Issue by helloxz** [P-St/Migrate2WinSSHTerm#4]
I used Windows 10, but found that the font overlapped. Please refer to the screenshot.

![](https://i.bmp.ovh/imgs/2018/12/ae6fa720a71efc64.png)

**Comment by P-St** [comment]
Did you change the font somewhere in your Windows settings? On my system (Win 10 1809) it looks like this
![winsshterm_preferences](https://user-images.githubusercontent.com/29782125/50512617-5724a380-0a93-11e9-8bd3-66e8480e0486.jpg)

**Comment by helloxz** [comment]
I am very glad to receive your reply, but I have not changed the font (Win 10 1809). My local default language is Chinese. Is this the reason?

**Comment by P-St** [comment]
I think the reason for the UI problems is the absence of the font "Segoe UI" on your Chinese Windows. You could try to install the font and see if this helps. However, Chinese letters are unfortunately not supported by this font.

**Comment by helloxz** [comment]
Thank you. I'll try.
