### ISSUE TITLE
mtPutty Migration

### ISSUE THREAD

**Issue by shoten** [P-St/Migrate2WinSSHTerm#5]
Hi!
I tried to use the migration tools to import my mPutty xml but the "save" box that allows to save the connexions.xml file never appears.
mtPutty version 1.6.0.176 BETA
I have serveral directories in the server tree  
Thanks !

**Comment by P-St** [comment]
Hi,
thanks for your bug report! I've just released version 0.8. If the problem still occurs, please post the content of the error message box here.

[Migrate2WinSSHTerm-0.8](https://github.com/P-St/Migrate2WinSSHTerm/releases/download/0.8/Migrate2WinSSHTerm-0.8.zip)
