### ISSUE TITLE
Feature Request: Add Kitty Support

### ISSUE THREAD

**Issue by mircsicz** [P-St/Migrate2WinSSHTerm#6]
Can you please look into adding support to import a kitty config, thtat would be awesome! ;-)

**Comment by P-St** [comment]
Hi, I've created a [new version](http://dl.winsshterm.net/Migrate2WinSSHTerm-0.10.zip) to support KiTTY classic. Does this work for you?

**Comment by mircsicz** [comment]
WOW, awesome how fast you added that option!!! But:
![Bildschirmfoto 2019-07-31 um 23 24 33](https://user-images.githubusercontent.com/7398305/62249508-dfcd3e80-b3ea-11e9-8850-59d30f3fcb18.png)

Last german line says: The system can't find the file...

**Comment by mircsicz** [comment]
And as I read the message: I'm not storing kitty's config in the registry. I've blocked that so I can sync my config using Seafile and have it on several machines. The path to the config is: %appdata%/KiTTY ;-)

**Comment by P-St** [comment]
KiTTY classic stores its sessions in the registry the same way PuTTY does, so it was no big deal to add support for KiTTY classic. However, for the portable version of KiTTY, which stores its sessions into files, it's not so easy. I'll see what I can do

**Comment by P-St** [comment]
Support for KiTTY was added in [this release](https://github.com/P-St/Migrate2WinSSHTerm/releases/tag/0.10)

**Comment by mircsicz** [comment]
Thank you for your effort!

I Just tried your latest release. It seems to be looking for a file named connections.xml which is (at least in my setup) nonexistent...

I've stored all connections in a folder structure like this:
[Screenshot 1](https://snag.gy/w6vTlk.jpg)
[Screenshot 2](https://snag.gy/gL08o5.jpg)
[Screenshot 2](https://snag.gy/i4Px7m.jpg)

Config Files in the Session Folder look like this:
[Pastebin](https://paste.debian.net/1095126/)

**Comment by P-St** [comment]
The connections.xml is the output file of the tool, as described under "Usage" in the Readme

**Comment by mircsicz** [comment]
LOL sorry seems it was too late to do such a test...

It triggered on the right directory it works like a charm! But if it's triggered on the launcher instead of sessions Dir it create's only empty entry's as the file's in the launcher Dir don't contain any data...

I knew that I was wrong when I saw it but that might not be true for other's...

Anyways THX a ton!

**Comment by P-St** [comment]
No problem, thanks for testing
