### ISSUE TITLE
MobaXTerm import error, multiple ssh22 entries

### ISSUE THREAD

**Issue by Brettflan** [P-St/Migrate2WinSSHTerm#8]
When trying to import from MobaXTerm, I receive this error:
`While reading from u'C:\\Users\\Me\\Documents\\MobaXterm\\MobaXterm.ini' [line 154]: option 'ssh22' in section u'Passwords' already exists`

Checking the file and line it indicates, there are indeed multiple entries in that section which start with "ssh22:", the second of which is at the line it's referring to. Each such line is different login info for different server accounts. It seems like your tool is only expecting a single one for some reason?

**Comment by P-St** [comment]
I'll see what I can do. Can you send the ini file to pst.freeware [at] gmail [dot] com?

**Comment by Brettflan** [comment]
OK, sent the file as requested, with keys/passwords and such slightly modified to be on the safe side but with structure unchanged.

**Comment by P-St** [comment]
Thanks, I tried to change the code. However, as the code is written in Python 2, which is now not supported any longer, I first have to migrate the code to Python 3.

I can run the tool without any error, if I delete all sections except "[Bookmarks]" from MobaXterm.ini. Does this work for you too?

**Comment by Brettflan** [comment]
Hmm, is that the important part? OK.

Tried what you suggested, made a copy of the file and deleted out all but the "[Bookmarks]" section, and ran it through. It did output a connections.xml file, but that file only had 3 entries out of the 10 that were in my Bookmarks section. The other 7 were missing.

**Comment by P-St** [comment]
Fixed with Commit 19f16e6c6298f0d0157a84ebff5bd4a7745b644d
